version: "3.3"
services:
  music-library-api-db:
    container_name: music-library-api-mysql-db
    image: jamielsharief/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "music_library_api_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-music-library-api-db:/var/lib/mysql
volumes:
  vol-music-library-api-db:
